### ISSUE TITLE
[2612/2413] Single-operator module with audio input for arbitrary FM

### ISSUE THREAD

**Issue by xandramax** [Kautenja/PotatoChips#69]
### Is your feature request related to a problem? Please describe.

I'd love to use [Algomorph](https://github.com/anlexmatos/FM-Delexander) in conjunction with the operators of a 2612 (or 2413), but their individual FM (phase) inputs and audio outputs are inaccessible.

### Describe the solution you'd like

It would be really neat to have a module something like the [Bogaudio FM-OP](https://library.vcvrack.com/Bogaudio/Bogaudio-FMOp), but containing an oscillator of one of these classic Yamaha FM chips. My thinking is that maybe the module could work by emulating two 2612/2413 operators, with the phase of one of them (the modulator) hijacked to be driven by external audio input rather than the chip's internal sine table. Ideally the other (carrier) operator would also have access to feedback. Like FM-OP, this theoretical module could also contain a built-in emulated 2612/2413 amplitude envelope.

I don't have any experience coding anything DSP or emulation related (besides noodling with the RAM in RackNES and the audio routing & cross-fading in Algomorph), so while I've taken a brief look into the 2612 code in this repository I'm not sure how feasible this module would actually be. What do you think?

**Comment by Kautenja** [comment]
No way, I had this same idea when I was looking through your post about Algomorph on the forum! I totally agree, this would be sweet. I think it's feasible with some refactoring of the existing code for 2612/2413, but will take some work. When I adopted the 2612 code from TercerBrazo, I fixed a few issues and managed to introduce some performance problems along the way. I plan to do some benchmarking and refactoring of that code anyway to get it back into better condition and will just rip the chip emulator apart into different modules that can be combined arbitrarily during that process.

**Comment by xandramax** [comment]
Excellent!

**Comment by Kautenja** [comment]
wrapped up a beta in the MiniBoss branch. I'm still working on the panel design and finalizing the features, but it's totally playable with Algomorph atm. See the https://github.com/Kautenja/PotatoChips/blob/MiniBoss/patches/debug/MiniBossAlgomorph.vcv patch for an example! I'll hopefully have this released by the end of the week.

**Comment by Kautenja** [comment]
@anlexmatos side note: Algomorph is sick!

**Comment by xandramax** [comment]
This is so cool!
