### ISSUE TITLE
Pallet Town Waves Missing Sync Pot

### ISSUE THREAD

**Issue by mjsyts** [Kautenja/PotatoChips#88]
Pallet Town Waves is missing noise sync pot in Rack
<img width="299" alt="Screen Shot 2021-05-31 at 11 50 49 AM" src="https://user-images.githubusercontent.com/77947318/120231533-7432a300-c206-11eb-9cff-d71329989205.png">

**Comment by mjsyts** [comment]
Stairs also missing input pots and attenuators

<img width="162" alt="Screen Shot 2021-06-01 at 3 27 51 PM" src="https://user-images.githubusercontent.com/77947318/120397867-f8138a80-c2ed-11eb-9fb6-a7a0864b196a.png">

**Comment by Kautenja** [comment]
Hi these were experimental features that haven't made it to release yet. I'll update the panels to alleviate any confusion until the features are implemented. Thanks for submitting the issue! I had forgotten about this.

**Comment by mjsyts** [comment]
Thanks Christian! I really like these modules. Keep up the good work, these are a blast.

**Comment by Kautenja** [comment]
Thanks, I'm glad you enjoy them! These panels have been fixed in https://github.com/Kautenja/PotatoChips/commit/ca007e0af583015dacef2c3ed9407474a9a36fb9 and will be released in the next few days to the library in version 1.11.0 (with the new module Blocks!).

**Comment by mjsyts** [comment]
Very cool! I made some similar emulators in SuperCollider, but your rack version is so much easier especially when you just want to make music quickly. Excited for the new release. I might try to make a video tutorial about these at some point, they're really useful!

**Comment by Kautenja** [comment]
Sick! I'm not very familiar with collider, but definitely love the intuitive interfacing capabilities of VCV. Also video tutorials would be killer. I'd considered making on for Boss Fight since the YM2612 is a bit weird to control on the envelopes, but always get wrapped up in other projects.

**Comment by mjsyts** [comment]
I wish I knew how to make rack plugins. The guide is not very helpful and I’m also not at all versed in C++ or whatever it was that Rack is using.

I think one of the things people would benefit from is understanding how to use an attenuverter for the noise source on some of these. If you don’t put the dial at 12:00, you can’t really do much with CV and it took me a second to figure that out.
