### ISSUE TITLE
VCV Rack v2 transition

### ISSUE THREAD

**Issue by firolightfog** [Kautenja/PotatoChips#92]
I'd like to encourage you to make the change. 
I miss your modules in Rack V2 library.
Best regards, Andras

**Comment by alefnull** [comment]
as a new Rack user as of Rack2, i never got to use them, but i just tried adding them all to my account via the library but was sad when none of them showed up in Rack.

**Comment by Kautenja** [comment]
Hello hello. Upgrades for Rackv2 are a priority, I've just been very busy recently and haven't had the time to revisit this project. Hopefully over the holidays there will be time to get a release out for v2.

**Comment by firolightfog** [comment]
Just take your time. Knowing that sooner or later we'll be able to experiment with your modules in V2 is a fantastic news!

**Comment by mjsyts** [comment]
Hey man, I've started developing a set of similar plugins and was wondering if we might be able to collaborate. I was going to email you but wasn't sure if you'd get it or not
<img width="1440" alt="Screen Shot 2022-02-21 at 2 03 00 PM" src="https://user-images.githubusercontent.com/77947318/155038364-49ebaf1b-0e22-461d-a73d-ef6ca571d899.png">
.

**Comment by firolightfog** [comment]
> Hello hello. Upgrades for Rackv2 are a priority, I've just been very busy recently and haven't had the time to revisit this project. Hopefully over the holidays there will be time to get a release out for v2.

Hallo,
Is there any update?

**Comment by Kautenja** [comment]
The code is compiling against Rack V2. The update is due as soon as the integration team has time to review the code!

**Comment by Kautenja** [comment]
@mjsyts feel free to email me! I love the design of your module.

**Comment by mjsyts** [comment]
Hey Christian,

I’d love to do some panel design for you if you like. My idea was to split the GB chip into three separate modules (pulse, noise, wave) and I like the design I have but a bit afraid it might violate some copyrights…
I was also a bit worried that if I made a wavetable VCO that people might end up whacking their speakers with DC offset but hey, it’s sort of an inherent risk right?

I’m also pretty new to C++ but so far so good. I’d love to work on some stuff with you if you’d be open to it.

M. Josiah Sytsma
Composer, Saxophonist, Educator, Repair Tech
***@***.***
